CREATE TABLE USERS(
  USERID CHAR(5) PRIMARY KEY,
  USERNAME VARCHAR(40) NOT NULL,
  MAILADDRESS VARCHAR(100) UNIQUE NOT NULL,
  PASSWORD VARCHAR(300) NOT NULL
);

CREATE TABLE WORKSPACE(
  WORKSPACEID CHAR(5) PRIMARY KEY,
  WORKSPACENAME VARCHAR(40) NOT NULL,
  CREATEDUSERID VARCHAR(5)NOT NULL
);

CREATE TABLE ROOMS(
  ROOMID VARCHAR(5) PRIMARY KEY,
  ROOMNAME VARCHAR(50) UNIQUE NOT NULL,
  CREATEDUSERID CHAR(5) NOT NULL,
  DIRECTED BOOLEAN DEFAULT FALSE,
  PRIVATED BOOLEAN DEFAULT FALSE,
  WORKSPACEID BPCHAR (5),
  FOREIGN KEY(WORKSPACEID) REFERENCES WORKSPACE(WORKSPACEID)
);

CREATE TABLE JOINROOM(
  ROOMID VARCHAR(5),
  USERID CHAR(5),
  PRIMARY KEY(ROOMID, USERID)
);

CREATE TABLE CHATLOG(
  CHATLOGID INTEGER PRIMARY KEY,
  ROOMID VARCHAR(5) NOT NULL,
  USERID CHAR(5) NOT NULL,
  MESSAGE VARCHAR(500),
  CREATED_AT TIMESTAMP,
  FOREIGN KEY (ROOMID) REFERENCES ROOMS(ROOMID),
  FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

CREATE TABLE JOINWORKSPACE(
  WORKSPACEID VARCHAR(5),
  USERID CHAR(5),
  PRIMARY KEY(WORKSPACEID, USERID)
);

CREATE TABLE WORKSPACEADMIN(
  WORKSPACEID VARCHAR(5),
  USERID VARCHAR(5),
  PRIMARY KEY(WORKSPACEID, USERID),
  FOREIGN KEY(WORKSPACEID) REFERENCES WORKSPACE(WORKSPACEID),
  FOREIGN KEY(USERID) REFERENCES USERS(USERID)
);

CREATE TABLE ROOMADMIN(
  ROOMID VARCHAR(5),
  USERID VARCHAR(5),
  PRIMARY KEY(ROOMID, USERID),
  FOREIGN KEY(ROOMID) REFERENCES ROOMS(ROOMID),
  FOREIGN KEY(USERID) REFERENCES USERS(USERID)
);

CREATE TABLE LOCKUSER(
  USERID VARCHAR(5) PRIMARY KEY,
  DAYTIME TIMESTAMP,
  FOREIGN KEY(USERID) REFERENCES USERS(USERID)
);

CREATE TABLE LOGINUSER(
  USERID VARCHAR(5) PRIMARY KEY,
  DAY DATE,
  FOREIGN KEY(USERID) REFERENCES USERS(USERID)
);

CREATE TABLE SESSIONID(
  USERID VARCHAR(5),
  WORKSPACEID VARCHAR(5),
  SESSIONID VARCHAR(500),
  PRIMARY KEY(USERID),
  FOREIGN KEY(USERID) REFERENCES USERS(USERID),
  FOREIGN KEY(WORKSPACEID) REFERENCES WORKSPACE(WORKSPACEID)
);

CREATE TABLE WORKSPACEMEMORY(
  USERID VARCHAR(5),
  WORKSPACEID VARCHAR(5),
  ROOMID VARCHAR(5),
  PRIMARY KEY(USERID,WORKSPACEID),
  FOREIGN KEY(USERID) REFERENCES USERS(USERID),
  FOREIGN KEY(WORKSPACEID) REFERENCES WORKSPACE(WORKSPACEID),
  FOREIGN KEY(ROOMID) REFERENCES ROOMS(ROOMID)
);

CREATE TABLE LOCKUSERCOUNT(
  USERID VARCHAR(5),
  CNT VARCHAR(1),
  PRIMARY KEY(USERID),
  FOREIGN KEY(USERID) REFERENCES USERS(USERID)
);
